version: '3.9'

services:
    shape-api:
        container_name: "ShapeAPI"
        build: 
            dockerfile: Dockerfile
            context: ShapeAPI
            target: ${TARGET}
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./ShapeAPI:/app
        ports:
            - ${PORT_API}:80
        