version: '3.9'

services:
    shape-api:
        container_name: "ShapeAPI"
        build: 
            dockerfile: Dockerfile
            context: ShapeAPI
            target: ${TARGET}
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./ShapeAPI:/app
            - /app/bin
            - /app/obj
        ports:
            - ${PORT_API}:80
        depends_on:
            - shape-bdd
            
    shape-bdd:
        container_name: "ShapeBDD"
        image: postgres
        restart: always
        volumes: 
            - shape-bdd:/var/lib/postgresql/data
        env_file: ./.env
        
    app-adminer:
        container_name: "ShapeAdminer"
        image: adminer
        restart: always
        ports:
            - ${PORT_ADMINER}:8080
        depends_on:
            - shape-bdd
volumes:
    shape-bdd: