// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShapeAPI.Data;

#nullable disable

namespace ShapeAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShapeAPI.Models.Shapes.BaseShape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ShapeGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShapeGroupId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("ShapeAPI.Models.Shapes.ShapeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ShapesGroups");
                });

            modelBuilder.Entity("ShapeAPI.Models.Shapes.BaseShape", b =>
                {
                    b.HasOne("ShapeAPI.Models.Shapes.ShapeGroup", null)
                        .WithMany("Shapes")
                        .HasForeignKey("ShapeGroupId");
                });

            modelBuilder.Entity("ShapeAPI.Models.Shapes.ShapeGroup", b =>
                {
                    b.Navigation("Shapes");
                });
#pragma warning restore 612, 618
        }
    }
}
